version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/apps/escalenzolink_src
file_exists_behavior: OVERWRITE
hooks:
    ApplicationStop:
        - location: scripts/stop_application.sh
          timeout: 30
          runas: ubuntu
    AfterInstall:
        - location: scripts/install.sh
          timeout: 300
          runas: ubuntu
    BeforeInstall:
        - location: scripts/clear_folder.sh
          timeout: 300
          runas: ubuntu
    ApplicationStart:
        - location: scripts/start_application.sh
          timeout: 300
          runas: ubuntu
