version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/apps
hooks:
    BeforeInstall:
        - location: /home/ubuntu/scripts/install_dependencies.sh
          timeout: 3000
          runas: root
    AfterInstall:
        - location: /home/ubuntu/scripts/change_permissions.sh
          timeout: 3000
          runas: root
    ApplicationStart:
        - location: /home/ubuntu/scripts/start_server.sh
          timeout: 3000
          runas: root
    ApplicationStop:
        - location: /home/ubuntu/scripts/stop_server.sh
          timeout: 3000
          runas: root
